apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- env-config.yaml

images:
- name: controller
  newName: quay.io/openshift-kni/oran-hwmgr-plugin
  newTag: 4.18.0

replacements:
- source:
    fieldPath: data.imagePullPolicy
    kind: ConfigMap
    name: env-config
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=manager].imagePullPolicy
    select:
      kind: Deployment
      name: controller-manager
